# Generated by Django 4.1 on 2023-11-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='wikipedia_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
